- added the necessary OpenCV macros for automated generation of Python code - I moved the definition of AKAZEOption into the AKAZE headers, that way OpenCV only needs to parse AKAZE.h. If it tries to parse config.h, then we get conflicting definitions with the rest of OpenCV, such as:
[100%] Building CXX object
modules/python/CMakeFiles/opencv_python.dir/src2/cv2.cpp.o
In file included from
/home/kevin/Imperial/PhD/OPENCV/opencv-2.4.8/modules/python/src2/cv2.cpp:1266:0:
/home/kevin/Imperial/PhD/OPENCV/opencv-2.4.8.build/modules/python/pyopencv_generated_const_reg.h:
In function ‘void initcv2()’:
/home/kevin/Imperial/PhD/OPENCV/opencv-2.4.8.build/modules/python/pyopencv_generated_const_reg.h:563:1:
error: reference to ‘SURF’ is ambiguous
In file included from
/home/kevin/Téléchargements/akaze-master/src/lib/AKAZE.h:13:0,
                 from
                 /home/kevin/Imperial/PhD/OPENCV/opencv-2.4.8/modules/python/src2/cv2.cpp:32:
                 /home/kevin/Téléchargements/akaze-master/src/lib/config.h:61:3:
                 error: candidates are: DESCRIPTOR_TYPE SURF
                 In file included from
                 /home/kevin/Imperial/PhD/OPENCV/opencv-2.4.8/modules/nonfree/include/opencv2/nonfree/nonfree.hpp:46:0,
                                  from
                                  /home/kevin/Imperial/PhD/OPENCV/opencv-2.4.8/modules/python/src2/cv2.cpp:35:
                                  /home/kevin/Imperial/PhD/OPENCV/opencv-2.4.8/modules/nonfree/include/opencv2/nonfree/features2d.hpp:107:20:
                                  error:                 class cv::SURF
                                  make[2]: ***
                                  [modules/python/CMakeFiles/opencv_python.dir/src2/cv2.cpp.o]
                                  Error 1
                                  make[1]: ***
                                  [modules/python/CMakeFiles/opencv_python.dir/all]
                                  Error 2
                                  make: *** [all] Error 2